server:
  port: 8180
spring:
  application:
    name: spring-boot-admin

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  context-path: /mgmt
  security.enabled: false

# tag::configuration-ui-hystrix[]
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
# end::configuration-ui-hystrix[]


security:
  user:
    name: buxiaoxia
    password: buxiaoxia
