# 端口
server:
  port: 8082
  compression:
    enabled: true
    min-response-size: 1KB
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  max-http-header-size: 102400
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  
spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false
    static-locations:
      - classpath:/static/
      - classpath:/static3/
      - classpath:/static2
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
#    settings.number_format: 0.##########
    settings:
      number_format: 0.##########
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: jun_code_freemarker
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # redis token信息
  redis:
    key:
      prefix:
        userToken: "user:token:"
        passwordError: "user:password:error:"
        permissionRefresh: "user:token:permissionRefresh:"
      expire:
        #userToken: 604800 # 7天 1*24*3600
        userToken: 86400 # 1天 1*24*3600
        passwordError: 3600 # 一个小时
        #permissionRefresh: 604800 # 7天 7*24*3600
        permissionRefresh: 86400 # 1天 1*24*3600
    allowMultipleLogin: true # 允许多处登陆

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  mapper-locations: classpath:mapper/${project.database}/**/*.xml,classpath:mapper/*.xml
  type-aliases-package: org.snaker.engine.entity
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: deleted
    enable-sql-runner: true

#使用代码生成模块时 指定要生成的表存在于哪种数据库，可选值有【mysql、oracle、sqlServer】
project:
  database: mysql

shiro:
  enable: false

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: 
  # 匹配链接
  urlPatterns: /system/*,/tool/*