# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: org.sqlite.JDBC
        druid:
            # 主库数据源
            master:
                # 发布后
                # url: jdbc:sqlite:./sqlite/code-generator.db
                # 开发时
                url: jdbc:sqlite::resource:static/sqlite/code-generator.db
                username: root
                password: password