
# 数据源配置
spring:
  profiles:
    active: dev
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: hapek521!
        url: jdbc:mysql://hupei.fun:39001/a_my-generator1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

server:
    port: 8998
# MyBatis配置
mybatis:
    # 搜索指定包别名
#    typeAliasesPackage: com.template.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:**/generator/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
