camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks
  database:
    type: mysql
    
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7061/eureka/
  instance:
      prefer-ip-address: true
      status-page-url-path: /swagger-ui.html
      
spring:
  application:
    name: camunda-demo-service
  jersey: 
    application-path: /engine-rest 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/camunda_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useOldAliasMetadataBehavior=true
    username: root
    password: 123456
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800